from codrone_edu.drone import *
drone = Drone()
drone.pair()
drone.takeoff()
drone.set_throttle(30)
drone.set_yaw(30)
drone.move(1)
drone.set_yaw(-30)
drone.move(2)
drone.set_throttle(-30)
drone.set_yaw(30)
drone.move(2)
drone.set_yaw(-30)
drone.move(1)
drone.land()
drone.close()